apiVersion: apps/v1
kind: Deployment
metadata:
  name: lesson8-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lesson8-app
  template:
    metadata:
      labels:
        app: lesson8-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
